services:
  - type: web
    name: storeline
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: storeline-db
          property: connectionString

databases:
  - name: storeline-db
    plan: free
