from .extensions import db
from .models import User, Store, InventoryItem


def seed_if_empty():
    """Populate first-run demo data: HQ admin, 3 stores, a store login per
    store, and a starter inventory catalog. Safe to call every boot —
    it only runs once, when the inventory items table is empty."""
    if InventoryItem.query.first():
        return

    stores = [
        Store(name="Angono Branch", location="Angono, Rizal", manager="J. Cruz"),
        Store(name="Taytay Branch", location="Taytay, Rizal", manager="R. Dela Pena"),
        Store(name="Cainta Branch", location="Cainta, Rizal", manager="L. Ramos"),
    ]
    db.session.add_all(stores)
    db.session.flush()

    items = [
        # WRAPPER
        InventoryItem(name="DONUT WRAPPER - PLASTIC", category="WRAPPER", unit="PCS", stock=100),
        InventoryItem(name="DONUT WRAPPER PAPER - 2024", category="WRAPPER", unit="PCS", stock=100),
        InventoryItem(name="BUNWICH PAPER -BACON", category="WRAPPER", unit="PCS", stock=100),
        InventoryItem(name="BUNWICH PAPER - HAM & CHEESE/TUNA", category="WRAPPER", unit="PCS", stock=100),
        InventoryItem(name="SAVE A WRAP", category="WRAPPER", unit="PCS", stock=100),
        InventoryItem(name="GREASE PROOF PAPER", category="WRAPPER", unit="PCS", stock=100),
        
        # BAGS
        InventoryItem(name="MINI BAG BIODEGRADABLE (2024)", category="BAGS", unit="PCS", stock=100),
        InventoryItem(name="DUNKIN MINI PAPER BAG", category="BAGS", unit="PCS", stock=100),
        InventoryItem(name="SMALL BAG BIODEGRADABLE (2024)", category="BAGS", unit="PCS", stock=100),
        InventoryItem(name="DUNKIN SMALL PAPER BAG", category="BAGS", unit="PCS", stock=100),
        InventoryItem(name="ECO BAG 20X24", category="BAGS", unit="PCS", stock=100),
        InventoryItem(name="ECO BAG 20X30", category="BAGS", unit="PCS", stock=100),
        
        # BOXES
        InventoryItem(name="HALF DOZEN BOX (CLASSIC)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="HALF DOZEN BOX (PREMIUM)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="DOZEN BOX (CLASSIC)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="DOZEN BOX (PREMIUM)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="MUNCHKINS BOX (5s)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="MUNCHKINS BOX (10s)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="MUNCHKINS BOX (50s)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="MUNCHKINS BOX (100s)", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="PASALUBONG BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="BUNWICH BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="PIE BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="MUFFIN BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="CAKE BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="BOX SLEEVE", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="TAKARA BOX", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="BOX HOLDER", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="SPECIAL BOX A", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="SPECIAL BOX B", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="EXTRA BOX LARGE", category="BOXES", unit="PCS", stock=100),
        InventoryItem(name="BOX MISC", category="BOXES", unit="PCS", stock=100),
        
        # PAPER CUPS/LIDS
        InventoryItem(name="HOT CUP 8OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="HOT CUP 12OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="HOT CUP LID 8OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="HOT CUP LID 12OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="COLD CUP 12OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="COLD CUP 16OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="COLD CUP 22OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="COLD CUP LID FLAT", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="COLD CUP LID DOME", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="PAPER STRAW", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="PLASTIC STRAW", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="STIRRER", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="CUP SLEEVE", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="CUP TRAY (2-compartment)", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="CUP TRAY (4-compartment)", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SHARING CUP", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SHARING LID", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="TAKE OUT TRAY", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="PAPER CUP 6OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="PAPER CUP LID 6OZ", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SAMPLE CUP", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="CUP HOLDER BAG", category="PAPER CUPS/LIDS", unit="PCS", stock=100),
        
        # HOT CUPS/LIDS
        InventoryItem(name="HOT CUP 10OZ", category="HOT CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="HOT CUP LID 10OZ", category="HOT CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="DOUBLE WALL CUP", category="HOT CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SIPPER LID", category="HOT CUPS/LIDS", unit="PCS", stock=100),
        
        # BOWL CUPS/LIDS
        InventoryItem(name="SOUP BOWL 12OZ", category="BOWL CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SOUP BOWL 16OZ", category="BOWL CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SOUP BOWL LID", category="BOWL CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SALAD BOWL", category="BOWL CUPS/LIDS", unit="PCS", stock=100),
        InventoryItem(name="SALAD BOWL LID", category="BOWL CUPS/LIDS", unit="PCS", stock=100),
        
        # BUNWICH FILLINGS
        InventoryItem(name="BACON SLICES", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="HAM SLICES", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="TUNA FLAKES", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="CHEESE SLICES", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="MAYONNAISE", category="BUNWICH FILLINGS", unit="PACK", stock=100),
        InventoryItem(name="BURGER BUNS", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="HOTDOG BUNS", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="HOTDOG", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="PATTY", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="EGG", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="BUTTER", category="BUNWICH FILLINGS", unit="PACK", stock=100),
        InventoryItem(name="MARGARINE", category="BUNWICH FILLINGS", unit="PACK", stock=100),
        InventoryItem(name="LETTUCE", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="TOMATOES", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="ONIONS", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="CUCUMBER", category="BUNWICH FILLINGS", unit="KG", stock=100),
        InventoryItem(name="PICKLES", category="BUNWICH FILLINGS", unit="JAR", stock=100),
        InventoryItem(name="BBQ SAUCE", category="BUNWICH FILLINGS", unit="BOT", stock=100),
        InventoryItem(name="KETCHUP", category="BUNWICH FILLINGS", unit="BOT", stock=100),
        InventoryItem(name="MUSTARD", category="BUNWICH FILLINGS", unit="BOT", stock=100),
        InventoryItem(name="SPECIAL DRESSING", category="BUNWICH FILLINGS", unit="PACK", stock=100),
        InventoryItem(name="FILLINGS MISC 1", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="FILLINGS MISC 2", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="FILLINGS MISC 3", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        InventoryItem(name="FILLINGS MISC 4", category="BUNWICH FILLINGS", unit="PCS", stock=100),
        
        # COFFEE
        InventoryItem(name="COFFEE BEANS", category="COFFEE", unit="KG", stock=100),
        InventoryItem(name="COFFEE GROUND", category="COFFEE", unit="KG", stock=100),
        InventoryItem(name="CREAMER", category="COFFEE", unit="PACK", stock=100),
        InventoryItem(name="SUGAR WHITE", category="COFFEE", unit="KG", stock=100),
        InventoryItem(name="SUGAR BROWN", category="COFFEE", unit="KG", stock=100),
        InventoryItem(name="SUGAR PACKET", category="COFFEE", unit="PCS", stock=100),
        InventoryItem(name="CONDENSED MILK", category="COFFEE", unit="CAN", stock=100),
        InventoryItem(name="EVAPORATED MILK", category="COFFEE", unit="CAN", stock=100),
        InventoryItem(name="ESPRESSO CAPSULE", category="COFFEE", unit="PCS", stock=100),
        InventoryItem(name="SYRUP VANILLA", category="COFFEE", unit="BOT", stock=100),
        InventoryItem(name="SYRUP CARAMEL", category="COFFEE", unit="BOT", stock=100),
        InventoryItem(name="SYRUP HAZELNUT", category="COFFEE", unit="BOT", stock=100),
        
        # HOT CHOCOLATE
        InventoryItem(name="CHOCOLATE POWDER", category="HOT CHOCOLATE", unit="PACK", stock=100),
        InventoryItem(name="MARSHMALLOWS", category="HOT CHOCOLATE", unit="PACK", stock=100),
        InventoryItem(name="CHOCO SYRUP", category="HOT CHOCOLATE", unit="BOT", stock=100),
        
        # OTHER BEVERAGES
        InventoryItem(name="ICED TEA POWDER", category="OTHER BEVERAGES", unit="PACK", stock=100),
        InventoryItem(name="JUICE CONCENTRATE", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="MILK TEA POWDER", category="OTHER BEVERAGES", unit="PACK", stock=100),
        InventoryItem(name="BLACK TEA BAGS", category="OTHER BEVERAGES", unit="PCS", stock=100),
        InventoryItem(name="GREEN TEA BAGS", category="OTHER BEVERAGES", unit="PCS", stock=100),
        InventoryItem(name="NATA DE COCO", category="OTHER BEVERAGES", unit="JAR", stock=100),
        InventoryItem(name="TAPIOCA PEARLS", category="OTHER BEVERAGES", unit="PACK", stock=100),
        InventoryItem(name="COCONUT JELLY", category="OTHER BEVERAGES", unit="JAR", stock=100),
        InventoryItem(name="FRUIT JELLY", category="OTHER BEVERAGES", unit="JAR", stock=100),
        InventoryItem(name="SINKERS MISC 1", category="OTHER BEVERAGES", unit="PCS", stock=100),
        InventoryItem(name="SINKERS MISC 2", category="OTHER BEVERAGES", unit="PCS", stock=100),
        InventoryItem(name="ICE CUBES", category="OTHER BEVERAGES", unit="BAG", stock=100),
        InventoryItem(name="CRUSHED ICE", category="OTHER BEVERAGES", unit="BAG", stock=100),
        InventoryItem(name="LEMON EXTRACT", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="CALAMANSI EXTRACT", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="SODA SYRUP COLA", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="SODA SYRUP SPRITE", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="SODA SYRUP ROYAL", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="CO2 TANK", category="OTHER BEVERAGES", unit="CYLINDER", stock=100),
        InventoryItem(name="BEVERAGE SYRUP A", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="BEVERAGE SYRUP B", category="OTHER BEVERAGES", unit="BOT", stock=100),
        InventoryItem(name="BEVERAGE MISC", category="OTHER BEVERAGES", unit="PCS", stock=100),
        
        # MINERAL WATER
        InventoryItem(name="MINERAL WATER 500ML", category="MINERAL WATER", unit="BOT", stock=100),
        
        # SOFTDRINKS
        InventoryItem(name="COKE 1.5L", category="SOFTDRINKS", unit="BOT", stock=100),
        InventoryItem(name="SPRITE 1.5L", category="SOFTDRINKS", unit="BOT", stock=100),
        InventoryItem(name="ROYAL 1.5L", category="SOFTDRINKS", unit="BOT", stock=100),
        InventoryItem(name="COKE CAN", category="SOFTDRINKS", unit="CAN", stock=100),
        InventoryItem(name="SPRITE CAN", category="SOFTDRINKS", unit="CAN", stock=100),
        InventoryItem(name="ROYAL CAN", category="SOFTDRINKS", unit="CAN", stock=100),
        
        # UTENSILS
        InventoryItem(name="TONGS SMALL", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="TONGS LARGE", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="TRAY PLASTIC", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="TRAY METAL", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SCOOP ICE", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SCOOP POWDER", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="WHISK", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SPATULA SILICONE", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SPATULA WOOD", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="KNIFE CHEF", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="KNIFE UTILITY", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="CUTTING BOARD", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="MEASURING CUP SET", category="UTENSILS", unit="SET", stock=100),
        InventoryItem(name="MEASURING SPOON SET", category="UTENSILS", unit="SET", stock=100),
        InventoryItem(name="PITCHER 2L", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="PITCHER 1L", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="DISPENSER SYRUP", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="DISPENSER SAUCE", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SQUEEZE BOTTLE", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="BOWL MIXING", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="CONTAINER STORAGE 5L", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="CONTAINER STORAGE 10L", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="CAN OPENER", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="SCISSORS", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="TIMER", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="THERMOMETER", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="APRON", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="HAIRNET", category="UTENSILS", unit="PACK", stock=100),
        InventoryItem(name="GLOVES DISPOSABLE", category="UTENSILS", unit="BOX", stock=100),
        InventoryItem(name="FACE MASK", category="UTENSILS", unit="BOX", stock=100),
        InventoryItem(name="RAGS CLEANING", category="UTENSILS", unit="PACK", stock=100),
        InventoryItem(name="SPONGE SCRUB", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="STEEL WOOL", category="UTENSILS", unit="PACK", stock=100),
        InventoryItem(name="BUCKET", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="MOP", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="BROOM", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="DUSTPAN", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 1", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 2", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 3", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 4", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 5", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 6", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 7", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 8", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 9", category="UTENSILS", unit="PCS", stock=100),
        InventoryItem(name="UTENSIL MISC 10", category="UTENSILS", unit="PCS", stock=100),
        
        # CLEANING MATERIALS
        InventoryItem(name="DISHWASHING LIQUID", category="CLEANING MATERIALS", unit="GAL", stock=100),
        InventoryItem(name="BLEACH", category="CLEANING MATERIALS", unit="GAL", stock=100),
        InventoryItem(name="MURIATIC ACID", category="CLEANING MATERIALS", unit="BOT", stock=100),
        InventoryItem(name="ALL PURPOSE CLEANER", category="CLEANING MATERIALS", unit="BOT", stock=100),
        InventoryItem(name="GLASS CLEANER", category="CLEANING MATERIALS", unit="BOT", stock=100),
        InventoryItem(name="FLOOR WAX", category="CLEANING MATERIALS", unit="CAN", stock=100),
        InventoryItem(name="DISINFECTANT SPRAY", category="CLEANING MATERIALS", unit="CAN", stock=100),
        InventoryItem(name="ALCOHOL 70%", category="CLEANING MATERIALS", unit="GAL", stock=100),
        InventoryItem(name="HAND SOAP LIQUID", category="CLEANING MATERIALS", unit="GAL", stock=100),
        InventoryItem(name="TRASH BAG LARGE", category="CLEANING MATERIALS", unit="PACK", stock=100),
        InventoryItem(name="TRASH BAG MEDIUM", category="CLEANING MATERIALS", unit="PACK", stock=100),
        InventoryItem(name="TRASH BAG SMALL", category="CLEANING MATERIALS", unit="PACK", stock=100),
        InventoryItem(name="TISSUE ROLL", category="CLEANING MATERIALS", unit="PACK", stock=100),
        InventoryItem(name="PAPER TOWEL", category="CLEANING MATERIALS", unit="PACK", stock=100),
        InventoryItem(name="SPONGE CLOTH", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 1", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 2", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 3", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 4", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 5", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 6", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 7", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 8", category="CLEANING MATERIALS", unit="PCS", stock=100),
        InventoryItem(name="CLEANING MISC 9", category="CLEANING MATERIALS", unit="PCS", stock=100),
        
        # OFFICE SUPPLIES
        InventoryItem(name="BALLPEN BLACK", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="BALLPEN BLUE", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="PENCIL", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="ERASER", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="STAPLER", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="STAPLE WIRE", category="OFFICE SUPPLIES", unit="BOX", stock=100),
        InventoryItem(name="TAPE SCOTCH", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="TAPE PACKAGING", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="LOGBOOK", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="RECEIPT BOOK", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="OFFICE MISC 1", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        InventoryItem(name="OFFICE MISC 2", category="OFFICE SUPPLIES", unit="PCS", stock=100),
        
        # PROMO ITEM
        InventoryItem(name="PROMO ITEM 1", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 2", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 3", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 4", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 5", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 6", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 7", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 8", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 9", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 10", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 11", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 12", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 13", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 14", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 15", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 16", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 17", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 18", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 19", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 20", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 21", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 22", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 23", category="PROMO ITEM", unit="PCS", stock=100),
        InventoryItem(name="PROMO ITEM 24", category="PROMO ITEM", unit="PCS", stock=100),
        
        # OTHERS / DUNKCREATION / MISCELLANEOUS
        InventoryItem(name="DUNKCREATION ITEM", category="DUNKCREATION", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 1", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 2", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 3", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 4", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 5", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 6", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 7", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 8", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 9", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 10", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 11", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 12", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 13", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 14", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 15", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 16", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 17", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="MISC ITEM 18", category="MISCELLANEOUS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 1", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 2", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 3", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 4", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 5", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 6", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 7", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 8", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 9", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 10", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 11", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 12", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 13", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 14", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 15", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 16", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 17", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 18", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 19", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 20", category="OTHERS", unit="PCS", stock=100),
        InventoryItem(name="OTHER ITEM 21", category="OTHERS", unit="PCS", stock=100),
    ]
    
    db.session.add_all(items)

    # Gawin lamang ito kung wala pang admin user
    if not User.query.filter_by(username="admin").first():
        admin = User(username="admin", role="admin")
        admin.set_password("admin123")
        db.session.add(admin)

    for s in stores:
        username = s.name.lower().replace(" ", "")
        if not User.query.filter_by(username=username).first():
            u = User(username=username, role="store", store=s)
            u.set_password("store123")
            db.session.add(u)

    db.session.commit()
